---
- name: add gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: disable docker service
  service:
    name: docker
    enabled: false
