---
- name: update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install system dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: add gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  register: docker_repo

- name: update apt-cache
  apt:
    update_cache: yes
  when: docker_repo | changed

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: disable docker service
  service:
    name: docker
    enabled: no
  when: lookup('env', 'MOLECULE_DRIVER_NAME') != 'docker'
